### ISSUE TITLE
Modded skills added don't have a slot, if  survivor had only one base of this skill type.

### ISSUE THREAD

**Issue by benjdidj** [KingEnderBrine/-RoR2-ExtendedLoadout#2]
I Know this is not supposed to work with modded skills.

i play with mods that add skills; like artificer extended,  new skills appear in the extended choices exept for row(s) of skills that had no vanilla alternative skill .

**Comment by benjdidj** [comment]
i forgot, also would it be possible to make it available for modded survivor.

**Comment by benjdidj** [comment]
![7mWbdoqtSf](https://user-images.githubusercontent.com/72584566/103570536-929ba900-4ec9-11eb-8b2a-fe845bf07a4a.png)
![Risk_of_Rain_2_VV036azFZs](https://user-images.githubusercontent.com/72584566/103570554-9deed480-4ec9-11eb-9582-c2b24ffbdd87.png)
As you can see there is no utility extended skills. I guess it is because in vanilla u didn't need to see the extended skill for one skill. So the added one for this skill type dont show.

In game the added skills work fine. thx for ur time.

**Comment by KingEnderBrine** [comment]
Each slot is added manually because I want to ensure that every vanilla skill works correctly (which is not the case for Engineer's turrets for example). I think I can add a config option, something like `Unsafe`, which will add an additional skill slot if a skill has at least 2 variants and a (modded) character doesn't already have extra slots taken. And if some skill doesn't work it's not my problem, since I can't add support for everything.

**Comment by KingEnderBrine** [comment]
Published an update that adds `Unsafe` mod, as I've described in the last comment

**Comment by benjdidj** [comment]
Wow that was quick :) yeah i guessed that you did what u did for good reason. thx very much.
