### ISSUE TITLE
 switch back and foreward between the 2 related skills like multi.

### ISSUE THREAD

**Issue by benjdidj** [KingEnderBrine/-RoR2-ExtendedLoadout#3]
i'd rather be able to switch beetween the 2 skills by pushing 1 2 3 4,and not having to hold the key  especially for m1's that you keep pressed most of the time. for sure ths mod is better for long cooldown skills.

**Comment by KingEnderBrine** [comment]
Can you elaborate on what you mean here?

**Comment by benjdidj** [comment]
rather than pushing the button to use the skill, i would like an option to switch between 2 skills. for example 1 to switch between m1 and alt m1, 2 to switch between m2 and alt m2, 3 to switch beetween dash and alternate dash, and 4 to swich between speecial and alt special. like with mult you push A to switch between the 2 different m1 and then click to use it. thx anyway.

**Comment by benjdidj** [comment]
![image](https://user-images.githubusercontent.com/72584566/103572779-6d109e80-4ecd-11eb-9330-197bde1eb826.png)

**Comment by KingEnderBrine** [comment]
This will not be done in either of these mods. Since you want `ExtraSkillSlots` to do not what it's designed for.

**Comment by benjdidj** [comment]
no worries. thx. there is a mod that do switching but you have to write something in the chat. not conveniant for fast switching. i wish i could code... doont u think the idea could be interresting ?

**Comment by KingEnderBrine** [comment]
Nah, that's fine, don't erase anything. I don't know if it would be interesting for other people, but it isn't for me. `ExtraSkillSlots` was originally written because one person in the Discord wanted to create a character with more than 4 skills, so it's was more for modded characters than vanilla. `ExpandedLoadout` was created because people were thinking `ExtraSkillSlots` does what currently `ExpandedLoadout` does, so I made it more clear that `ExtraSkillSlots` is a library.

**Comment by benjdidj** [comment]
thx for answering.
