### ISSUE TITLE
Modded character doesn't have the extra loadouts

### ISSUE THREAD

**Issue by DeltaTheWize** [KingEnderBrine/-RoR2-ExtendedLoadout#5]
So I got this mod and got it to work with most of my modded characters but for some reason the Goku mod, Vegeta mod, Trunks mod those mods despite me changing the config they did not allow me to have extra skills anyway to fix this? I was thinking maybe they were based on like captain or one of the other characters if that was the issue code wise, or maybe it is the custom UI that causes the issue for them.
![Screenshot 2021-02-15 195507](https://user-images.githubusercontent.com/79126705/108016566-b8879380-6fc7-11eb-8d43-3ab2c3ddef02.png)

**Comment by KingEnderBrine** [comment]
Well, I've looked at the problem and it's entirely on `KingModUtilities` side. If you want these mods to work together you should report this to Kinggrinyov. Can't say if he will do something with this, but you can point him out that the issue is in his `MainPlugin` class in `LoadoutPanelController_Rebuild_Custom` method. That's the most I can do with that issue.
